# প্রোজেক্ট ২ঃ রিগ্রেশন প্রবলেম (Boston House Price dataset)

আমরা এই প্রজেক্টে একটি রিগ্রেশন প্রবলেম সলভ করব । এর জন্য আমরা Boston House Price dataset টি বেছে নিয়েছি। পরবর্তীতে আমরা আরেকটি রিগ্রেশন প্রবলেম সলভ করব। 

মেশিন লার্নিং প্রজেক্ট চেকলিস্ট দেখা  যাক - 

১) প্রবলেম ডেফিনেশন ( প্রবলেম ও ডেটাসেট সম্পর্কে বিস্তারিত জানা) 

২) ডেটাসেট লোড করা। 

৩) এনালাইজ ডেটা (ডেসক্রিপ্টিভ স্ট্যাটিস্টিক্স ও ডেটা ভিজ্যুয়ালাইজেশন ) 

৪) ভ্যালিডেশন ডেটা সেট (ডেটাসেটকে স্প্লিট করা)

৫) ইভ্যালুয়েট এলগরিফদম ( ডেটাকে প্রিপ্রসের না করে) 

৬) ইভ্যালুয়েট এলগরিফদম ( ডেটাকে প্রিপ্রসের করে)

৭) ইম্প্রুভ রেজাল্ট  ( প্যারামিটার টিউনিং করে) 

৮) এনস্যাম্বল মেথড ব্যবহার করে মডেলের এক্যুরেসি বাড়ানো

৯) টিউনিং এনস্যাম্বল মেথড। 

১০) ফাইনালাইজ মডেল।

 Python Project Template
 
 
 1. Prepare Problem
 
 a) Load libraries
 
 b) Load dataset


 2. Summarize Data
 
 a) Descriptive statistics
 
 b) Data visualizations


 3. Prepare Data
 
 a) Data Cleaning
 
 b) Feature Selection
 
 c) Data Transforms


 4. Evaluate Algorithms
 
 a) Split-out validation dataset
 
 b) Test options and evaluation metric
 
 c) Spot Check Algorithms
 
 d) Compare Algorithms
 

 5. Improve Accuracy
 
 a) Algorithm Tuning
 
 b) Ensembles
 

 6. Finalize Model
 
 a) Predictions on validation dataset
 
 b) Create standalone model on entire training dataset
 
 c) Save model for later use

   # ধাপঃ ১ 

# ২.১ প্রবলেম ডেফিনেশন ( প্রবলেম ও ডেটাসেট সম্পর্কে বিস্তারিত জানা)

আমরা এখানে Boston House Price dataset নিয়ে কাজ করব। এই ডেটাসেটটির প্রতিটি সারি বা রেকর্ড দ্বারা boston এর বিভিন্ন এলাকার সম্পর্কে ধারনা দেয়। বিভিন্ন এলাকার বাসা ভাড়া বিভিন্ন হয়। এর তারতম্য হওয়ার কিছু কারন রয়েছে। যাদেরকে আমর ফিচার বলি।  নিম্নে ফিচারগুলো  সম্পর্কে ধারনা দেওয়া হল। 

1. CRIM: per capita crime rate by town

2. ZN: proportion of residential land zoned for lots over 25,000 sq.ft.

3. INDUS: proportion of non-retail business acres per town

4. CHAS: Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)

5. NOX: nitric oxides concentration (parts per 10 million)

6. RM: average number of rooms per dwelling

7. AGE: proportion of owner-occupied units built prior to 1940

8. DIS: weighted distances to five Boston employment centers

9. RAD: index of accessibility to radial highways

10. TAX: full-value property-tax rate per $10,000

11. PTRATIO: pupil-teacher ratio by town

12. B: 1000(Bk − 0.63)2 where Bk is the proportion of blacks by town

13. LSTAT: % lower status of the population

14. MEDV: Median value of owner-occupied homes in $1000s

তাহলে আমরা জানতে পারলাম ফিচারের কোন নাম দ্বারা কি বুঝায়। এখন আমাদের এই ব্যপারটা নিয়ে আরেক্টু ঘাটাঘাটি করে জ্ঞান নিতে হবে।

# ২.২ ডেটাসেট ও দরকারি লাইব্রেরি লোড করা 

১) আমরা pandas ব্যবহার করে ডেটাসেট লোড করব এবং ডেটাসেটের অন্যান্য কাজ করব।

২) ডেটা ভিজ্যুয়ালাইজেশনের জন্য আমরা matplotlib, seaborn এবং plotly ব্যবহার করব। 

৩) রিগ্রেশন সমস্যা সমাধানের জন্য বহুল ব্যবহৃত এলগরিদম ব্যবহার করব -- 

     Linear Regression.
    
     Ridge Regression.
    
     LASSO Linear Regression.
    
     Elastic Net Regression.
    
     k-Nearest Neighbors.

     Classification and Regression Trees.

     Support Vector Machines.
    
৪) পারফর্মেন্স দেখার জন্য যে রিগ্রেশন ম্যাট্রিক্স ব্যবহার করব 
    
     Mean Squared Error.
    
     R2
    
৫) মডেলের পার্ফমেন্স আরো ভালো করার জন্য যে এনসেম্বল এলগরিদম ব্যবহার করব 
    
    RandomForestRegressor
    
    GradientBoostingRegressor
    
    ExtraTreesRegressor
    
    AdaBoostRegressor

In [8]:
# Load libraries

# for load dataset
import numpy as np
from numpy import arange
import pandas as pd
from pandas import set_option
from sklearn import datasets

# for data visualisation
import matplotlib.pyplot as plt
import seaborn as sns
import cufflinks as cf
cf.go_offline()
%matplotlib inline

# data preparation and evaluation model
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

# Machine learning algorithm and pipeline
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.pipeline import Pipeline

# Ensemble model
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.metrics import mean_squared_error

/Users/user/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning:

numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

In [23]:
# Load dataset
boston = datasets.load_boston()

   # ধাপঃ ২

# ২.৩ ডেটা বিশ্লেষণ ( Descriptive statistics)

 প্রথমেই দেখে নি আমরা ডেটাসেটের বিস্তারিত ধারনা নিয়ে নেই । কয়টি অব্জারভেশন (সারি) এবং কয়টি ফিচার (কলাম) আছে সেই সম্পর্কে একটা ধারনা নেওয়া যাক।

In [26]:
boston = pd.DataFrame(boston.data, columns=boston.feature_names)

In [28]:
boston.head(20)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3.0,222.0,18.7,394.12,5.21
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,19.15
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,15.2,386.71,17.10
10,0.22489,12.5,7.87,0.0,0.524,6.377,94.3,6.3467,5.0,311.0,15.2,392.52,20.45
11,0.11747,12.5,7.87,0.0,0.524,6.009,82.9,6.2267,5.0,311.0,15.2,396.90,13.27
12,0.09378,12.5,7.87,0.0,0.524,5.889,39.0,5.4509,5.0,311.0,15.2,390.50,15.71
13,0.62976,0.0,8.14,0.0,0.538,5.949,61.8,4.7075,4.0,307.0,21.0,396.90,8.26
14,0.63796,0.0,8.14,0.0,0.538,6.096,84.5,4.4619,4.0,307.0,21.0,380.02,10.26
15,0.62739,0.0,8.14,0.0,0.538,5.834,56.5,4.4986,4.0,307.0,21.0,395.62,8.47
16,1.05393,0.0,8.14,0.0,0.538,5.935,29.3,4.4986,4.0,307.0,21.0,386.85,6.58
17,0.78420,0.0,8.14,0.0,0.538,5.990,81.7,4.2579,4.0,307.0,21.0,386.75,14.67
18,0.80271,0.0,8.14,0.0,0.538,5.456,36.6,3.7965,4.0,307.0,21.0,288.99,11.69
19,0.72580,0.0,8.14,0.0,0.538,5.727,69.5,3.7965,4.0,307.0,21.0,390.95,11.28

In [29]:
boston.shape

(506, 13)

In [32]:
boston.dtypes

CRIM       float64
ZN         float64
INDUS      float64
CHAS       float64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD        float64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
dtype: object

In [34]:
boston.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000

In [35]:
boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
dtypes: float64(13)
memory usage: 51.5 KB